### ISSUE TITLE
[建议]没法同步

### ISSUE THREAD

**Issue by zhaogd233** [riskers/GithubX#8]
我用不同的电脑，不能同步过来。而且token 过期之后，再次申请也会丢失数据对吗。
能不能写一个gist 保持下数据呢。或者告知下本地保存的数据在哪。能覆盖同步吗。

**Comment by riskers** [comment]
* token 过期再次申请不会丢失数据
* 多设备不能同步这个问题，目前在开发一个后端 API 解决，写 gist 不是一个好办法

**Comment by riskers** [comment]
可以尝试新版本，不过需要自己部署 https://github.com/riskers/GithubX/blob/master/README-cn.md#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8
