### ISSUE TITLE
[BUG] 左侧导航树同一tag重复出现

### ISSUE THREAD

**Issue by yuzhichang** [riskers/GithubX#9]
左侧导航树同一tag重复出现，例如出现了两次"eoi"。见如下截图：
![Screenshot_2022-05-21_12-16-36](https://user-images.githubusercontent.com/153784/169635046-4ccec9cc-dd6f-4bde-8c35-ea3cfe02aa7b.png)

**Comment by riskers** [comment]
已经修复，不会再创建已经存在的 tag
